#
# SPDX-FileCopyrightText: 2024 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Check for conventional commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-for-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@f1823f632e95a64547566dcd2c7da920e67117ad # v2.0.1
